### ISSUE TITLE
Consider Trademark guide (and maybe other things) from UNICEF Innovation Inventory as a resource.

### ISSUE THREAD

**Issue by kfogel** [unicef/publicgoods-toolkit#58]
[PR #80 in the UNICEF Innovation Inventory](https://github.com/unicef/inventory/pull/80) repository contains some trademark advice that we should review and consider adding as a resource, once it's merged.

Also, there may be other things in the Inventory that deserve a closer look!

**Comment by jwflory** [comment]
Oh hi @kfogel, what a surprise to see you here! 😀 Thanks for the shout-out here.

**Comment by sstruble** [comment]
I included mention of this trademark resource in the Resources + Tools Appendix. I didn't feel that other content from that Inventory merited incorporation at this point because of a mix of reasons: some is still rudimentary or in early stages of being fleshed out, some didn't seem immediately relevant, and I feel there's enough content at this point in the toolkit for readers to digest. New additions should be guided by feedback from target audience. And I'm sure UNICEF will make sure these two resources develop cross-links as needed in the future!
